/**
 * @file index.js
 */

/**
 * Create Vivy subscription plugin
 * @returns {{onRegisterModel: onRegisterModel, onUnregisterModel: onUnregisterModel}}
 */
export default function VivySubscription() {

    // All unsubscriptions generated by subscriptions in models
    const unsubscriptions = {};

    /**
     * Register subscriptions in models
     * @param store {Object}
     * @param nameSpace {string}
     * @param subscriptions {Array}
     */
    function registerSubscriptions(store, nameSpace, subscriptions) {

        if (!store || !nameSpace || !subscriptions || subscriptions.length < 1) {
            return;
        }

        subscriptions.forEach(subscription => {

            if (!unsubscriptions.hasOwnProperty(nameSpace)) {
                unsubscriptions[nameSpace] = [];
            }

            unsubscriptions[nameSpace].push(
                subscription({
                    history: store.history
                })(store.dispatch, store.getState)
            );

        });

    }

    /**
     * Unregister subscriptions in models
     * @param store {Object}
     * @param nameSpace {string}
     */
    function unregisterSubscriptions(store, nameSpace) {

        if (
            !store || !nameSpace
            || !unsubscriptions?.[nameSpace] || unsubscriptions[nameSpace].length < 1
        ) {
            return;
        }

        unsubscriptions[nameSpace].forEach(unsubscription => unsubscription?.());

    }

    return {

        /**
         * Register subscriptions when register a Vivy model
         * @param model {Object}
         * @param store {Object}
         */
        onRegisterModel: (model, store) => {

            if (!model || !store) {
                return;
            }

            const {nameSpace, subscriptions} = model;

            // Register subscriptions
            if (subscriptions?.length > 0) {
                registerSubscriptions(store, nameSpace, subscriptions || []);
            }

        },

        /**
         * Unregister subscriptions when unregister a Vivy model
         * @param model {Object}
         * @param store {Object}
         */
        onUnregisterModel: (model, store) => {

            if (!model || !store) {
                return;
            }

            const {nameSpace, subscriptions} = model;

            // Unregister subscriptions
            if (subscriptions?.length > 0) {
                unregisterSubscriptions(store, nameSpace);
            }

        }

    };

}
